{{- if .Values.ingress.enabled -}}
{{- $fullName := include "poc-spring.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "poc-spring.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - poc-spring.maxilog.tech
      secretName: poc-spring-secret-tls
  {{- end }}
  rules:
    - host: poc-spring.maxilog.tech
      http:
        paths:
          - path: /websocket/(.*)
            pathType: Prefix
            backend:
              service:
                name: notification
                port:
                  number: 80
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: front
                port:
                  number: 80
{{- end }}

