spring:
  profiles:
    active: prod
  cloud:
    schema-registry-client:
      endpoint: http://localhost:8881
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: maxilog-product-user
    password: maxilog-product-password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
keycloak:
  url: http://keycloak:8080
  realm: local