elasticsearch:
  client:
    replicas: 1
  master:
    replicas: 2
  data:
    replicas: 1
logstash:
  elasticsearch:
    host: elk-elasticsearch-client
  service:
    ports:
      syslog-tcp:
        port: 1514
        targetPort: syslog-tcp
        protocol: TCP
  ports:
    - name: syslog-tcp
      containerPort: 1514
      protocol: TCP
  inputs:
    main: |-
      input {
        tcp {
            port => 1514
            type => syslog
            codec => json_lines
        }
      }

kibana:
  enabled: true
  image:
    tag: "6.8.6"
  env:
    ELASTICSEARCH_HOSTS: http://elk-elasticsearch-client:9200
  files:
    kibana.yml:
      elasticsearch.hosts: http://elk-elasticsearch-client:9200
  ingress:
    enabled: true
    hosts:
      - "kibana.maxilog.me"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - hosts:
          - kibana.maxilog.me
        secretName: kibana.maxilog.me-tls
