apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-customer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.customer.replicaCount }}
  selector:
    matchLabels:
      app: customer
      {{- include "poc-spring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: customer
        {{- include "poc-spring.labels" . | nindent 8 }}
    spec:
      serviceAccountName: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: customer
          image: "{{ .Values.customer.image.repository }}:{{ .Values.customer.image.tag }}"
          ports:
            - containerPort: 8081
          imagePullPolicy: {{ .Values.customer.image.pullPolicy }}
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            httpGet:
              path: /management/health
              port: 8080
          env:
            {{ include "poc-spring.consulEnvirementConfig" . | nindent 12 }}
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_REALM
            - name: LOGSTASH_ENABLED
              value: {{ .Values.customer.logstash.enabled | quote}}
            - name: LOGSTASH_HOST
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: LOGSTASH_HOST
            - name: LOGSTASH_PORT
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: LOGSTASH_PORT