apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.customer.service.type }}
  ports:
    - port: {{ .Values.customer.service.port }}
      targetPort: 8081
  selector:
    app: customer