def label = "worker-${UUID.randomUUID().toString()}"

podTemplate(
        label: label,
        containers: [
                containerTemplate(name: 'maven', image: 'maven:3.6.3-openjdk-11', command: 'cat', ttyEnabled: true),
                containerTemplate(name: 'node', image: 'node:14.4', command: 'cat', ttyEnabled: true),
                containerTemplate(name: 'kaniko', image: 'gcr.io/kaniko-project/executor:debug', command: '/busybox/cat', ttyEnabled: true),
                containerTemplate(name: 'kubectl', image: 'bitnami/kubectl:1.20.2', command: 'cat', ttyEnabled: true)
        ],
        volumes: [
                hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock')
        ]) {
    node(label) {
        stage('Checkout') {
            def myRepo = checkout scm
            def gitCommit = myRepo.GIT_COMMIT
            def gitBranch = myRepo.GIT_BRANCH
            def shortGitCommit = "${gitCommit[0..10]}"
            def previousGitCommit = sh(script: "git rev-parse ${gitCommit}~", returnStdout: true)
            def version = 'latest'
        }
        dir("front-angular") {
            container('maven') {
                version = sh script: 'mvn help:evaluate -Dexpression=project.version -q -DforceStdout', returnStdout: true
                version = version.substring(0, version.length() - 9)
            }
            try {
                stage('Build') {
                    container('node') {
                        sh 'npm install'
                        sh 'npm run build'
                    }
                }
                stage('Create Docker images') {
                    container('kaniko') {
                        withCredentials([usernamePassword(credentialsId: 'nexus', passwordVariable: 'NEXUS_PASSWORD', usernameVariable: 'NEXUS_USERNAME')]) {
                            def credentials = sh(script: "printf \"%s:%s\" \"${NEXUS_USERNAME}\" \"${NEXUS_PASSWORD}\" | base64 | tr -d '\n'", returnStdout: true)
                            sh "echo '{\"auths\":{\"docker.maxilog.me\":{\"auth\":\"${credentials}\"}}}' > /kaniko/.docker/config.json"
                            sh "/kaniko/executor --dockerfile Dockerfile --context `pwd`/  --insecure --skip-tls-verify --cache=true --destination=docker.maxilog.me/poc/spring/front:${version}"
                        }
                    }
                }
            } catch (e) {
                currentBuild.result = "FAILED"
                throw e
            } finally {

            }
        }
    }
}
