---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: gateway
          image: docker.maxilog.tech/poc/spring/gateway:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /management/health
              port: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod, kubernetes
#            - name: SPRING_CLOUD_CONSUL_HOST
#              valueFrom:
#                configMapKeyRef:
#                  name: consul-config
#                  key: SPRING_CLOUD_CONSUL_HOST
#            - name: SPRING_CLOUD_CONSUL_PORT
#              valueFrom:
#                configMapKeyRef:
#                  name: consul-config
#                  key: SPRING_CLOUD_CONSUL_PORT
#            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME
#              value: customer
#            - name: SPRING_CLOUD_CONSUL_DISCOVERY_PORT
#              value: '80'
           - name: KEYCLOAK_URL
             valueFrom:
               configMapKeyRef:
                 name: keycloak-config
                 key: KEYCLOAK_URL
           - name: KEYCLOAK_REALM
             valueFrom:
               configMapKeyRef:
                 name: keycloak-config
                 key: KEYCLOAK_REALM
           - name: LOGSTASH_ENABLED
             value: 'true'
           - name: LOGSTASH_HOST
             valueFrom:
               configMapKeyRef:
                 name: logstash-config
                 key: LOGSTASH_HOST
           - name: LOGSTASH_PORT
             valueFrom:
               configMapKeyRef:
                 name: logstash-config
                 key: LOGSTASH_PORT