spring:
  profiles:
    active: prod
  cloud:
    schema-registry-client:
      endpoint: http://localhost:8881
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification
      username: adminmaxilog
      password: adminmaxilog2020
keycloak:
  url: http://keycloak:8080
  realm: local