spring:
  profiles:
    active: dev
  cloud:
    schema-registry-client:
      endpoint: http://localhost:8881
  data:
    mongodb:
      #uri: mongodb://adminmaxilog:adminmaxilog2020@localhost:27017/notification
      uri: mongodb://localhost:27017/notification
      username: adminmaxilog
      password: adminmaxilog2020
keycloak:
  url: http://localhost:8180
  realm: local
logstash:
  enabled: false
  host: localhost
  port: 5000
