spring:
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /management/health
        instanceId: notification:${spring.application.instance-id:${random.value}}
        service-name: notification
      config:
        watch:
          enabled: true
    schema-registry-client:
      endpoint: http://localhost:8881
  data:
    mongodb:
      #uri: mongodb://adminmaxilog:adminmaxilog2020@localhost:27017/notification
      uri: mongodb://localhost:27017/notification
      username: adminmaxilog
      password: adminmaxilog2020
keycloak:
  url: http://localhost:8180
  realm: local
