{{- if .Values.gateway.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            httpGet:
              path: /management/health
              port: 8080
          env:
            {{ include "poc-spring.consulEnvirementConfig" . | nindent 12 }}
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_REALM
            - name: LOGSTASH_ENABLED
              value: {{ .Values.customer.logstash.enabled | quote}}
            - name: LOGSTASH_HOST
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: LOGSTASH_HOST
            - name: LOGSTASH_PORT
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: LOGSTASH_PORT
{{- end -}}