version: '3.1'
services:

  kong-database:
    image: postgres:11.5
    container_name: kong-database
    volumes:
      - kong-volume:/var/lib/postgresql/data
    restart: on-failure
    tty: true
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB:       kong
      POSTGRES_USER:     kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net

  kong-migration:
    image: kong:1.4.0-oidc
    command: "kong migrations bootstrap"
    container_name: kong-migration
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net
    links:
      - kong-database
    restart: on-failure

  kong-config:
    build:
      dockerfile: Dockerfile
      context: config
    container_name: kong-config
    depends_on:
      - kong
    environment:
      KONG_DATABASE: postgres
    networks:
      - kong-net
    links:
      - kong-database
    restart: on-failure

  kong:
    image: kong:1.4.0-oidc
    container_name: kong
    restart: always
    depends_on:
      - kong-migration
      - kong-database
    networks:
      - kong-net
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-database
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      kong
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      kong
      KONG_PROXY_LISTEN:     0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN:     0.0.0.0:8001
      KONG_PLUGINS:          bundled,oidc
      KONG_LOG_LEVEL:        debug

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    depends_on:
      - kong-database
    volumes:
      - ./config/:/tmp/config/
    networks:
      - kong-net
    ports:
      - "1337:1337"
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_DATABASE: konga
      DB_USER: kong
      DB_PASSWORD: kong
      KONGA_SEED_USER_DATA_SOURCE_FILE: /tmp/config/kong-user.data
      KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE: /tmp/config/kong-node.data
      NODE_ENV: development

networks:
  kong-net:
    driver: bridge
volumes:
  kong-volume: