{{- if .Values.order.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.order.replicaCount }}
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      serviceAccountName: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: order
          image: docker.maxilog.me/poc/spring/order:1.0.0
          ports:
            - containerPort: 8084
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            httpGet:
              path: /management/health
              port: 8084
          env:
            {{ include "poc-spring.consulEnvirementConfig" . | nindent 12 }}
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_REALM
            - name: LOGSTASH_ENABLED
              value: {{ .Values.customer.logstash.enabled | quote}}
            - name: LOGSTASH_HOST
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: LOGSTASH_HOST
            - name: LOGSTASH_PORT
              valueFrom:
                configMapKeyRef:
                  name: logstash-config
                  key: LOGSTASH_PORT
            - name: SPRING_DATASOURCE_DB
              value: order
            - name: SPRING_DATASOURCE_USERNAME
              value: maxilog-order-user
            - name: SPRING_DATASOURCE_PASSWORD
              value: maxilog-order-password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://database-postgresql:5432/$(SPRING_DATASOURCE_DB)
            - name: SPRING_CLOUD_SCHEMA_REGISTRY_CLIENT_ENDPOINT
              value: http://{{ .Release.Name }}-cp-schema-registry:8081
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              value: {{ .Release.Name }}-cp-kafka:9092
{{- end -}}
