{{- if .Values.order.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.order.service.type }}
  ports:
    - port: 80
      targetPort: 8084
  selector:
    app: order
{{- end -}}