global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /management/prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          # On MacOS, replace localhost by host.docker.internal
          - localhost:8080
          - localhost:8081
          - localhost:8082
          - localhost:8083
          - localhost:8084