---
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: customer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: docker.maxilog.tech/poc/spring/customer:1.0.0
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONSUL_HOST
              value: consul-consul-server
            - name: SPRING_CLOUD_CONSUL_PORT
              value: '8500'
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME
              value: customer
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_PORT
              value: '80'
            - name: KEYCLOAK_URL
              value: https://auth.maxilog.tech
            - name: KEYCLOAK_REALM
              value: poc
            - name: LOGSTASH_ENABLED
              value: 'false'
            - name: LOGSTASH_HOST
              value: logstash
            - name: LOGSTASH_PORT
              value: '1514'