---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: docker.maxilog.tech/poc/spring/gateway:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONSUL_HOST
              value: consul-server
            - name: SPRING_CLOUD_CONSUL_PORT
              value: '8500'
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME
              value: gateway
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_PORT
              value: '80'
            - name: KEYCLOAK_URL
              value: https://auth.maxilog.tech
            - name: KEYCLOAK_REALM
              value: poc