def label = "worker-${UUID.randomUUID().toString()}"

podTemplate(
        label: label,
        containers: [
                containerTemplate(name: 'helm', image: 'kubernautslabs/helm-kubectl', command: 'cat', doc: true)
        ]) {
    node(label) {
        dir("kubernetes/helm") {
            container('helm') {
                try {
                    stage('Package') {
                        sh 'helm package ./'
                    }
                    stage('Push') {
                        sh 'curl -u jenkins:jenkins http://nexus.maxilog.tech/repository/helm/ --upload-file poc-spring-*.tgz -v'
                    }
                } catch (e) {
                    currentBuild.result = "FAILED"
                    throw e
                } finally {

                }
            }

        }
    }
}