def label = "worker-${UUID.randomUUID().toString()}"

podTemplate(
        label: label,
        containers: [
                containerTemplate(name: 'helm', image: 'kubernautslabs/helm-kubectl', command: 'cat', ttyEnabled: true)
        ]) {
    node(label) {
        stage('Checkout') {
            checkout scm
        }
        dir("kubernetes/helm") {
            container('helm') {
                try {
                    stage('Package') {
                        sh 'helm dependency build'
                        sh 'helm package .'
                    }
                    stage('Push') {
                        withCredentials([usernamePassword(credentialsId: 'nexus', passwordVariable: 'NEXUS_PASSWORD', usernameVariable: 'NEXUS_USERNAME')]) {
                            sh 'curl -u ${NEXUS_USERNAME}:${NEXUS_PASSWORD} http://nexus.maxilog.me/repository/helm/ --upload-file poc-spring-*.tgz -v'
                        }
                    }
                } catch (e) {
                    currentBuild.result = "FAILED"
                    throw e
                } finally {

                }
            }

        }
    }
}
