# Default values for poc-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

front:
  image:
    repository: docker.maxilog.tech/poc/spring/front
    pullPolicy: Always
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 80

gateway:
  enabled: true
  replicaCount: 1
  image:
    repository: docker.maxilog.tech/poc/spring/gateway
    pullPolicy: Always
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 80
  logstash:
    enabled: false

customer:
  replicaCount: 1
  image:
    repository: docker.maxilog.tech/poc/spring/customer
    pullPolicy: Always
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 80
  logstash:
    enabled: false

notification:
  enabled: true
  replicaCount: 1
  image:
    repository: docker.maxilog.tech/poc/spring/notification
    pullPolicy: Always
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 80
  logstash:
    enabled: false

order:
  enabled: true
  replicaCount: 1
  image:
    repository: docker.maxilog.tech/poc/spring/order
    pullPolicy: Always
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 80
  logstash:
    enabled: false

product:
  enabled: true
  replicaCount: 1
  image:
    repository: docker.maxilog.tech/poc/spring/product
    pullPolicy: Always
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 80
  logstash:
    enabled: false

consul:
  enabled: false

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local










resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
