apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.front.service.type }}
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: front