apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ .Release.Namespace }}
data:
  KEYCLOAK_URL: {{ include "poc-spring.keycloak.url" . | quote }}
  KEYCLOAK_REALM: {{ .Values.keycloak.realm }}
