apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-config
  namespace: {{ .Release.Namespace }}
data:
  KEYCLOAK_URL: {{ .Values.keycloak.url}}
  KEYCLOAK_REALM: {{ .Values.keycloak.realm}}
