spring:
  profiles:
    active: prod
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    schema-registry-client:
      endpoint: http://localhost:8881
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: maxilog-order-user
    password: maxilog-order-password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
keycloak:
  url: http://keycloak:8080
  realm: local